server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mingqi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.itcast.service.domain
